[package]
name = "balloon"
version = "0.1.0"
authors = ["Vivek Ghaisas <v.a.ghaisas@gmail.com>"]
build = "build.rs"

[build-dependencies]
peg = { version = "0.5" }

[dependencies]
ansi_term = "0.9.0"
rustyline = "1.0.0"
fnv = "1.0.5"
